const CONFIG={
  // Endpoint, który możesz podpiąć do Twojego Cloudflare Workera.
  transactionsApi:"https://exodo-api.oliwierdawidowicz.workers.dev/api/exo/transactions",
  // Fallback do istniejącego endpointu, jeśli Worker zwróci 404.
  legacyApi:"https://exodo-api.oliwierdawidowicz.workers.dev/api/recent?limit=50",
  startAt:"2026-09-02T18:00:00+02:00",endAt:"2026-09-02T20:30:00+02:00",drawAt:"2026-09-02T21:00:00+02:00"
};
let transactions=[],filter="qualified";
const $=s=>document.querySelector(s);const esc=v=>String(v??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;let n=Number(String(v??0).replace(/\s/g,"").replace(/zł|\$/gi,"").replace(/,/g,"."));return Number.isFinite(n)?n:0};
const money=v=>num(v).toLocaleString("pl-PL",{maximumFractionDigits:2})+"$";const exoFmt=v=>num(v).toLocaleString("pl-PL",{maximumFractionDigits:2});
function lotsFor(x){x=num(x);if(x<20)return 0;if(x<50)return 1;if(x<100)return 3;if(x<150)return 7;if(x<200)return 12;if(x===200)return 16;return 0}
function normalizeTx(data){let a=Array.isArray(data)?data:(data?.transactions||data?.recent||data?.data||[]);return a.map((x,i)=>{const type=String(x.type||x.action||x.kind||x.side||"").toLowerCase();const nick=x.nick||x.name||x.player||x.username||x.playerName||"Nieznany";const shares=num(x.shares??x.amount??x.exo??x.quantity??x.actions);const value=num(x.value??x.price??x.total??x.cost);return {id:x.id||x.transaction_id||x.txid||`${nick}-${shares}-${value}-${x.timestamp||x.time||i}`,nick,shares,value,type:type.includes("sprzed")||type.includes("sell")?"sell":"buy",time:x.timestamp||x.time||x.created_at||"—"};}).filter(x=>x.shares>0&&x.nick.toLowerCase()!=="exo"&&x.nick.toLowerCase()!=="git");}
function qualified(){const map=new Map();for(const t of transactions){if(t.type!=="buy")continue;const d=map.get(t.nick)||{nick:t.nick,exo:0,value:0};d.exo+=t.shares;d.value+=t.value;map.set(t.nick,d)}return [...map.values()].map(x=>({...x,lots:lotsFor(x.exo),qualified:x.exo>=20&&x.exo<=200,reason:x.exo<20?"PONIŻEJ 20 EXO":x.exo>200?"LIMIT 200 EXO":"ZAKWALIFIKOWANY"})).sort((a,b)=>b.lots-a.lots||b.exo-a.exo)}
function render(){const p=qualified(),q=p.filter(x=>x.qualified),list=p.filter(x=>filter==='all'||filter==='qualified'&&x.qualified||filter==='rejected'&&!x.qualified);$("#participantsCount").textContent=q.length;$("#lots").textContent=q.reduce((s,x)=>s+x.lots,0);$("#exo").textContent=exoFmt(q.reduce((s,x)=>s+x.exo,0));$("#value").textContent=money(q.reduce((s,x)=>s+x.value,0));$("#participantRows").innerHTML=list.length?list.map((x,i)=>`<div class="tr"><span class="row-muted">${i+1}</span><span class="row-name">${esc(x.nick)}</span><span>${exoFmt(x.exo)}</span><span><b>${x.lots}</b></span><span>${money(x.value)}</span><span class="status ${x.qualified?'ok':'bad'}">${x.qualified?'✓ OK':'✕ '+x.reason}</span></div>`).join(""):`<div class="empty">Brak uczestników.</div>`;$("#transactionsList").innerHTML=transactions.slice(0,50).map(t=>`<div class="tx"><span class="type ${t.type==='buy'?'buy':'sell'}">${t.type==='buy'?'KUPNO':'SPRZEDAŻ'}</span><div><b>${esc(t.nick)}</b><small>${t.time}</small></div><div><b>${exoFmt(t.shares)} EXO</b><small>${money(t.value)}</small></div></div>`).join("")||`<div class="empty">Brak dostępnych transakcji.</div>`;$("#updated").textContent=new Date().toLocaleTimeString("pl-PL");}
async function load(){try{$("#sourceStatus").style.color='var(--green)';let r=await fetch(CONFIG.transactionsApi,{cache:"no-store"});if(!r.ok)throw 0;transactions=normalizeTx(await r.json());render()}catch(e){try{let r=await fetch(CONFIG.legacyApi,{cache:"no-store"});if(!r.ok)throw 0;transactions=normalizeTx(await r.json());render();$("#sourceStatus").style.color='var(--red)'}catch(e2){transactions=[];render();$("#sourceStatus").style.color='var(--red)'}}}
function countdown(){const n=Date.now(),s=new Date(CONFIG.startAt).getTime(),e=new Date(CONFIG.endAt).getTime(),d=new Date(CONFIG.drawAt).getTime();let target,label,phase;if(n<s){target=s;label='DO STARTU LOTERII';phase='OCZEKIWANIE'}else if(n<e){target=e;label='DO KOŃCA LOTERII';phase='LOTERIA LIVE'}else if(n<d){target=d;label='LOSOWANIE ZA';phase='ZAKUPY ZAMKNIĘTE'}else{target=n;label='🎉 LOSOWANIE W TOKU';phase='LOSOWANIE'}$("#timerLabel").textContent=label;$("#phase").textContent=phase;const z=Math.max(0,target-n),h=Math.floor(z/36e5),m=Math.floor(z%36e5/6e4),s2=Math.floor(z%6e4/1e3);$("#timer").textContent=[h,m,s2].map(x=>String(x).padStart(2,'0')).join(':');$("#timerDate").textContent=new Date(target).toLocaleString('pl-PL')}
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});$("#refresh").onclick=load;load();countdown();setInterval(countdown,1000);setInterval(load,15000);
