const API_BASE="https://exodo-api.oliwierdawidowicz.workers.dev";
const CHALLENGE_URL=`${API_BASE}/api/challenge/state`,JOIN_URL=`${API_BASE}/api/challenge/join`,ANSWER_URL=`${API_BASE}/api/challenge/answer`,TRANSACTIONS_URL=`${API_BASE}/api/exo/transactions`,POLL_MS=5000;
let challengeState=null,marketTransactions=[],market=null;
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
const nick=()=>localStorage.getItem("exodo_challenge_nick")||"",saveNick=n=>localStorage.setItem("exodo_challenge_nick",n);
function n(v,d=2){return Number(v||0).toLocaleString("pl-PL",{maximumFractionDigits:d})}function money(v){return`${n(v,2)}$`}
function date(iso){if(!iso)return"—";const d=new Date(iso);return Number.isNaN(d.getTime())?"—":d.toLocaleString("pl-PL",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"})}
function clock(ms){const x=Math.max(0,ms),h=Math.floor(x/36e5),m=Math.floor(x%36e5/6e4),s=Math.floor(x%6e4/1e3);return[h,m,s].map(v=>String(v).padStart(2,"0")).join(":")}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function status(ok,t){const e=$("#apiStatus");e.classList.toggle("ok",ok);e.classList.toggle("error",!ok);$("#apiStatusText").textContent=t;$("#footerState").textContent=`API: ${t}`}
function compact(v){const x=Number(v);if(!Number.isFinite(x))return"—";if(Math.abs(x)>=1e6)return`${n(x/1e6,2)} mln`;if(Math.abs(x)>=1e3)return`${n(x/1e3,1)} tys.`;return n(x,2)}
async function loadAll(){try{const[sr,tr]=await Promise.all([fetch(`${CHALLENGE_URL}?t=${Date.now()}`,{cache:"no-store"}),fetch(`${TRANSACTIONS_URL}?t=${Date.now()}`,{cache:"no-store"})]);if(!sr.ok)throw new Error(`Challenge HTTP ${sr.status}`);const s=await sr.json();if(!s.ok)throw new Error(s.error||"Challenge API error");challengeState=s;if(tr.ok){const t=await tr.json();marketTransactions=Array.isArray(t.all_transactions)?t.all_transactions:(t.transactions||[]);market=t.market||null}render();status(true,s.challenge?.active?"CHALLENGE LIVE":"ONLINE");$("#syncText").textContent=`Aktualizacja ${new Date().toLocaleTimeString("pl-PL")} • co 5 s`}catch(e){console.error(e);status(false,"BŁĄD API")}}
function render(){const c=challengeState?.challenge||{};$("#eventId").textContent=c.id||"—";$("#eventStart").textContent=date(c.started_at);$("#eventEnd").textContent=date(c.end_at);const b=$("#eventStateBadge");b.classList.toggle("online",!!c.active);b.classList.toggle("offline",!c.active);b.querySelector("span").textContent=c.active?"LIVE":"OFFLINE";countdown();renderMarket();renderTx();renderBoard();renderStage()}
function countdown(){const c=challengeState?.challenge||{},l=$("#countdownLabel"),v=$("#countdown"),s=$("#countdownSub"),bar=$("#progressBar");if(!c.started_at||!c.end_at){l.textContent="STATUS KONKURSU";v.textContent="--:--:--";s.textContent="Konkurs nie został uruchomiony";bar.style.width="0%";return}const now=Date.now(),st=new Date(c.started_at).getTime(),en=new Date(c.end_at).getTime();if(now<st){l.textContent="DO STARTU";v.textContent=clock(st-now);s.textContent=`Start: ${date(c.started_at)}`;bar.style.width="0%";return}if(now<en&&c.active){l.textContent="DO KOŃCA KONKURSU";v.textContent=clock(en-now);s.textContent="Rozwiązuj etapy jak najszybciej";bar.style.width=`${Math.min(100,Math.max(0,(now-st)/(en-st)*100))}%`;return}l.textContent="KONKURS ZAKOŃCZONY";v.textContent="00:00:00";s.textContent="Ranking został zamrożony";bar.style.width="100%"}
function renderMarket(){if(!market)return;$("#marketPrice").textContent=Number.isFinite(Number(market.price))?`${n(market.price,2)}$`:"—";$("#marketLiquidity").textContent=Number.isFinite(Number(market.liquidity))?`${compact(market.liquidity)}$`:"—";$("#marketRating").textContent=market.rating||"—";$("#marketCommission").textContent=Number.isFinite(Number(market.commission))?`${n(market.commission,2)}%`:"—";$("#marketShares").textContent=Number.isFinite(Number(market.shares_in_circulation))?`${n(market.shares_in_circulation,2)} EXO`:"—"}
function renderTx(){const box=$("#recentEvents");if(!marketTransactions.length){box.innerHTML='<div class="empty">Brak aktualnych transakcji EXO.</div>';return}box.innerHTML=marketTransactions.slice(0,30).map(e=>{const sell=e.type==="sell";return`<div class="event-row ${sell?"market-sell":""}"><div><div class="event-name"><span class="market-type ${sell?"sell":""}">${sell?"SPRZEDAŻ":"KUPNO"}</span>${esc(e.nick)}</div><div class="event-info">${n(Math.abs(Number(e.shares||0)),2)} EXO ${e.time&&e.time!=="—"?` • ${esc(e.time)}`:""}</div></div><div class="event-value"><strong>${sell?"-":"+"}${n(Math.abs(Number(e.shares||0)),2)} EXO</strong><small>${money(Math.abs(Number(e.value||0)))}</small></div></div>`}).join("")}
function renderBoard(){const rows=challengeState?.leaderboard||[],stages=challengeState?.challenge?.stages_count||0;$("#statParticipants").textContent=rows.length;$("#statFinished").textContent=rows.filter(x=>x.finished_at).length;$("#statStages").textContent=stages;const me=rows.find(x=>String(x.nick).toLowerCase()===nick().toLowerCase());$("#statMyProgress").textContent=me?`${me.completed_stages}/${stages}`:`0/${stages}`;const b=$("#leaderboardBody");if(!rows.length){b.innerHTML='<tr><td colspan="5" class="table-empty">Brak uczestników.</td></tr>';return}b.innerHTML=rows.map((p,i)=>`<tr><td>${i+1}</td><td><span class="player-name">${esc(p.nick)}</span></td><td><span class="progress-chip"><b>${p.completed_stages}</b> / ${stages}</span></td><td><span class="${p.finished_at?"finished":p.completed_stages?"in-progress":"waiting"}">${p.finished_at?"✓ UKOŃCZONE":p.completed_stages?"W TRAKCIE":"OCZEKUJE"}</span></td><td>${p.finished_at?date(p.finished_at):"—"}</td></tr>`).join("")}
function renderStage(){const meNick=nick(),rows=challengeState?.leaderboard||[],stages=challengeState?.stages||[];$("#identityBox").textContent=meNick?`Zapisany nick: ${meNick}`:"Nie jesteś jeszcze zapisany na tym urządzeniu.";const me=rows.find(x=>String(x.nick).toLowerCase()===meNick.toLowerCase()),i=me?me.completed_stages:0;$("#stageBadge").textContent=`${Math.min(i+1,stages.length)}/${stages.length||0}`;if(!meNick){$("#stageTitle").textContent="Najpierw dołącz";$("#stagePrompt").textContent="Wpisz nick i zapisz się do konkursu.";return}if(!challengeState?.challenge?.active){$("#stageTitle").textContent="Konkurs nieaktywny";$("#stagePrompt").textContent="Poczekaj na rozpoczęcie kolejnego eventu.";return}if(me?.finished_at){$("#stageTitle").textContent="Challenge ukończony";$("#stagePrompt").textContent="Twój wynik jest zapisany w rankingu.";return}const s=stages[i];$("#stageTitle").textContent=s?.title||"Oczekiwanie";$("#stagePrompt").textContent=s?.prompt||"Brak aktywnego etapu."}
async function join(){const x=$("#nickInput").value.trim();if(!/^[A-Za-z0-9_]{3,16}$/.test(x)){toast("Podaj poprawny nick Minecraft.");return}try{const r=await fetch(JOIN_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nick:x})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Nie udało się dołączyć");saveNick(x);$("#nickInput").value="";const eb=$("#eligibilityBox");if(eb){eb.className="eligibility ok";eb.textContent=`Zweryfikowano: ${n(d.holdings,2)} EXO — możesz brać udział.`;}toast("Dołączono do konkursu.");await loadAll()}catch(e){toast(e.message)}}
async function answer(){const x=nick(),a=$("#answerInput").value.trim();if(!x){toast("Najpierw dołącz do konkursu.");return}if(!a){toast("Wpisz odpowiedź.");return}try{const r=await fetch(ANSWER_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nick:x,answer:a})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Błędna odpowiedź");$("#answerInput").value="";$("#answerStatus").className="answer-status ok";$("#answerStatus").textContent=d.finished?"Challenge ukończony!":"Poprawnie — kolejny etap odblokowany.";toast(d.finished?"Ukończyłeś challenge!":"Poprawna odpowiedź.");await loadAll()}catch(e){$("#answerStatus").className="answer-status bad";$("#answerStatus").textContent=e.message}}
$("#joinBtn").addEventListener("click",join);$("#answerBtn").addEventListener("click",answer);$("#answerInput").addEventListener("keydown",e=>{if(e.key==="Enter")answer()});$("#nickInput").addEventListener("keydown",e=>{if(e.key==="Enter")join()});
loadAll();setInterval(loadAll,POLL_MS);setInterval(countdown,1000);